export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS'
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'

export const CART_LIST_REQUEST = 'CART_LIST_REQUEST'
export const CART_LIST_SUCCESS = 'CART_LIST_SUCCESS'
export const CART_LIST_FAIL = 'CART_LIST_FAIL'

export const CART_DELETE_REQUEST = 'CART_DELETE_REQUEST'
export const CART_DELETE_SUCCESS = 'CART_DELETE_SUCCESS'
export const CART_DELETE_FAIL = 'CART_DELETE_FAIL'

export const SHIPPING_ADD_REQUEST = 'SHIPPING_ADD_REQUEST'