export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'
export const RESET_CART = 'RESET_CART'

export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST'
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS'
export const GET_ORDER_FAIL = 'GET_ORDER_FAIL'

export const CANCEL_ORDER_REQUEST = 'CANCEL_ORDER_REQUEST'
export const CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS'
export const CANCEL_ORDER_FAIL = 'CANCEL_ORDER_FAIL'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'

export const ORDER_LIST_MY_REQUEST = 'ORDER_LIST_MY_REQUEST'
export const ORDER_LIST_MY_SUCCESS = 'ORDER_LIST_MY_SUCCESS'
export const ORDER_LIST_MY_FAIL = 'ORDER_LIST_MY_FAIL'
export const ORDER_LIST_MY_RESET = 'ORDER_LIST_MY_RESET'

export const ORDER_DELIVER_REQUEST = 'ORDER_DELIVER_REQUEST'
export const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS'
export const ORDER_DELIVER_FAIL = 'ORDER_DELIVER_FAIL'
export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET'

// Admin Order
export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL'

export const ORDER_LIST_DETAIL_REQUEST = 'ORDER_LIST_DETAIL_REQUEST'
export const ORDER_LIST_DETAIL_SUCCESS = 'ORDER_LIST_DETAIL_SUCCESS'
export const ORDER_LIST_DETAIL_FAIL = 'ORDER_LIST_DETAIL_FAIL'

export const ORDER_ALL_REQUEST = 'ORDER_ALL_REQUEST'
export const ORDER_ALL_SUCCESS = 'ORDER_ALL_SUCCESS'
export const ORDER_ALL_FAIL = 'ORDER_ALL_FAIL'

export const ORDER_DETAIL_REQUEST = 'ORDER_DETAIL_REQUEST'
export const ORDER_DETAIL_SUCCESS = 'ORDER_DETAIL_SUCCESS'
export const ORDER_DETAIL_FAIL = 'ORDER_DETAIL_FAIL'

export const ORDER_SET_DELEVERY_REQUEST = 'ORDER_SET_DELEVERY_REQUEST'
export const ORDER_SET_DELEVERY_SUCCESS = 'ORDER_SET_DELEVERY_SUCCESS'
export const ORDER_SET_DELEVERY_FAIL = 'ORDER_SET_DELEVERY_FAIL'

export const ORDER_SET_PAID_REQUEST = 'ORDER_SET_PAID_REQUEST'
export const ORDER_SET_PAID_SUCCESS = 'ORDER_SET_PAID_SUCCESS'
export const ORDER_SET_PAID_FAIL = 'ORDER_SET_PAID_FAIL'

export const ORDER_PROFIT_REQUEST = 'ORDER_PROFIT_REQUEST'
export const ORDER_PROFIT_SUCCESS = 'ORDER_PROFIT_SUCCESS'
export const ORDER_PROFIT_FAIL = 'ORDER_PROFIT_FAIL'

// Shipper
// Find all Order Process
export const SHIPPER_ORDER_ALL_PROCESS_REQUEST = 'SHIPPER_ORDER_ALL_PROCESS_REQUEST'
export const SHIPPER_ORDER_ALL_PROCESS_SUCCESS = 'SHIPPER_ORDER_ALL_PROCESS_SUCCESS'
export const SHIPPER_ORDER_ALL_PROCESS_FAIL = 'SHIPPER_ORDER_ALL_PROCESS_FAIL'

// Find all Order States
export const SHIPPER_ORDER_ALL_STATE_REQUEST = 'SHIPPER_ORDER_ALL_STATE_REQUEST'
export const SHIPPER_ORDER_ALL_STATE_SUCCESS = 'SHIPPER_ORDER_ALL_STATE_SUCCESS'
export const SHIPPER_ORDER_ALL_STATE_FAIL = 'SHIPPER_ORDER_ALL_STATE_FAIL'

// Detail Order By Shipper
export const SHIPPER_ORDER_DETAIL_REQUEST = 'SHIPPER_ORDER_DETAIL_REQUEST'
export const SHIPPER_ORDER_DETAIL_SUCCESS = 'SHIPPER_ORDER_DETAIL_SUCCESS'
export const SHIPPER_ORDER_DETAIL_FAIL = 'SHIPPER_ORDER_DETAIL_FAIL'

// Choose Order By Shipper
export const SHIPPER_ORDER_CHOOSE_REQUEST = 'SHIPPER_ORDER_CHOOSE_REQUEST'
export const SHIPPER_ORDER_CHOOSE_SUCCESS = 'SHIPPER_ORDER_CHOOSE_SUCCESS'
export const SHIPPER_ORDER_CHOOSE_FAIL = 'SHIPPER_ORDER_CHOOSE_FAIL'

// Paid Order By Shipper
export const SHIPPER_ORDER_PAID_REQUEST = 'SHIPPER_ORDER_PAID_REQUEST'
export const SHIPPER_ORDER_PAID_SUCCESS = 'SHIPPER_ORDER_PAID_SUCCESS'
export const SHIPPER_ORDER_PAID_FAIL = 'SHIPPER_ORDER_PAID_FAIL'

// Cancel Order By Shipper
export const SHIPPER_ORDER_CANCEL_REQUEST = 'SHIPPER_ORDER_CANCEL_REQUEST'
export const SHIPPER_ORDER_CANCEL_SUCCESS = 'SHIPPER_ORDER_CANCEL_SUCCESS'
export const SHIPPER_ORDER_CANCEL_FAIL = 'SHIPPER_ORDER_CANCEL_FAIL'