// Category Admin
export const PRODUCT_CATEGORY_ADMIN_REQUEST = 'PRODUCT_CATEGORY_ADMIN_REQUEST'
export const PRODUCT_CATEGORY_ADMIN_SUCCESS = 'PRODUCT_CATEGORY_ADMIN_SUCCESS'
export const PRODUCT_CATEGORY_ADMIN_FAIL = 'PRODUCT_CATEGORY_ADMIN_FAIL'

export const PRODUCT_CATEGORY_DETAIL_ADMIN_REQUEST = 'PRODUCT_CATEGORY_DETAIL_ADMIN_REQUEST'
export const PRODUCT_CATEGORY_DETAIL_ADMIN_SUCCESS = 'PRODUCT_CATEGORY_DETAIL_ADMIN_SUCCESS'
export const PRODUCT_CATEGORY_DETAIL_ADMIN_FAIL = 'PRODUCT_CATEGORY_DETAIL_ADMIN_FAIL'

export const CREATE_CATEGORY_ADMIN_REQUEST = 'CREATE_CATEGORY_ADMIN_REQUEST'
export const CREATE_CATEGORY_ADMIN_SUCCESS = 'CREATE_CATEGORY_ADMIN_SUCCESS'
export const CREATE_CATEGORY_ADMIN_FAIL = 'CREATE_CATEGORY_ADMIN_FAIL'
export const CREATE_CATEGORY_ADMIN_RESET = 'CREATE_CATEGORY_ADMIN_RESET'

export const BLOCK_CATEGORY_ADMIN_REQUEST = 'BLOCK_CATEGORY_ADMIN_REQUEST'
export const BLOCK_CATEGORY_ADMIN_SUCCESS = 'BLOCK_CATEGORY_ADMIN_SUCCESS'
export const BLOCK_CATEGORY_ADMIN_FAIL = 'BLOCK_CATEGORY_ADMIN_FAIL'

export const UNLOCK_CATEGORY_ADMIN_REQUEST = 'UNLOCK_CATEGORY_ADMIN_REQUEST'
export const UNLOCK_CATEGORY_ADMIN_SUCCESS = 'UNLOCK_CATEGORY_ADMIN_SUCCESS'
export const UNLOCK_CATEGORY_ADMIN_FAIL = 'UNLOCK_CATEGORY_ADMIN_FAIL'

// 
export const PRODUCT_CATEGORY_REQUEST = 'PRODUCT_CATEGORY_REQUEST'
export const PRODUCT_CATEGORY_SUCCESS = 'PRODUCT_CATEGORY_SUCCESS'
export const PRODUCT_CATEGORY_FAIL = 'PRODUCT_CATEGORY_FAIL'

export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

// Admin
export const PRODUCT_ALL_REQUEST = 'PRODUCT_ALL_REQUEST'
export const PRODUCT_ALL_SUCCESS = 'PRODUCT_ALL_SUCCESS'
export const PRODUCT_ALL_FAIL = 'PRODUCT_ALL_FAIL'

export const PRODUCT_LIST_ADMIN_REQUEST = 'PRODUCT_LIST_ADMIN_REQUEST'
export const PRODUCT_LIST_ADMIN_SUCCESS = 'PRODUCT_LIST_ADMIN_SUCCESS'
export const PRODUCT_LIST_ADMIN_FAIL = 'PRODUCT_LIST_ADMIN_FAIL'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'

export const PRODUCT_LOCK_REQUEST = 'PRODUCT_LOCK_REQUEST'
export const PRODUCT_LOCK_SUCCESS = 'PRODUCT_LOCK_SUCCESS'
export const PRODUCT_LOCK_FAIL = 'PRODUCT_LOCK_FAIL'

export const PRODUCT_UNLOCK_REQUEST = 'PRODUCT_UNLOCK_REQUEST'
export const PRODUCT_UNLOCK_SUCCESS = 'PRODUCT_UNLOCK_SUCCESS'
export const PRODUCT_UNLOCK_FAIL = 'PRODUCT_UNLOCK_FAIL'

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST'
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS'
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL'
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET'

export const PRODUCT_DELETE_IMAGE_REQUEST = 'PRODUCT_DELETE_IMAGE_REQUEST'
export const PRODUCT_DELETE_IMAGE_SUCCESS = 'PRODUCT_DELETE_IMAGE_SUCCESS'
export const PRODUCT_DELETE_IMAGE_FAIL = 'PRODUCT_DELETE_IMAGE_FAIL'

export const PRODUCT_ADD_IMAGE_REQUEST = 'PRODUCT_ADD_IMAGE_REQUEST'
export const PRODUCT_ADD_IMAGE_SUCCESS = 'PRODUCT_ADD_IMAGE_SUCCESS'
export const PRODUCT_ADD_IMAGE_FAIL = 'PRODUCT_ADD_IMAGE_FAIL'

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS'
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET'

// Review
export const PRODUCT_GET_REVIEW_REQUEST = 'PRODUCT_GET_REVIEW_REQUEST'
export const PRODUCT_GET_REVIEW_SUCCESS = 'PRODUCT_GET_REVIEW_SUCCESS'
export const PRODUCT_GET_REVIEW_FAIL = 'PRODUCT_GET_REVIEW_FAIL'

export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST'
export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS'
export const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL'
export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET'

export const PRODUCT_TOP_REQUEST = 'PRODUCT_TOP_REQUEST'
export const PRODUCT_TOP_SUCCESS = 'PRODUCT_TOP_SUCCESS'
export const PRODUCT_TOP_FAIL = 'PRODUCT_TOP_FAIL'

// Admin - Review
export const ADMIN_GET_ALL_REVIEW_REQUEST = 'ADMIN_GET_ALL_REVIEW_REQUEST'
export const ADMIN_GET_ALL_REVIEW_SUCCESS = 'ADMIN_GET_ALL_REVIEW_SUCCESS'
export const ADMIN_GET_ALL_REVIEW_FAIL = 'ADMIN_GET_ALL_REVIEW_FAIL'

export const REVIEW_LOCK_REQUEST = 'REVIEW_LOCK_REQUEST'
export const REVIEW_LOCK_SUCCESS = 'REVIEW_LOCK_SUCCESS'
export const REVIEW_LOCK_FAIL = 'REVIEW_LOCK_FAIL'

export const REVIEW_UNLOCK_REQUEST = 'REVIEW_UNLOCK_REQUEST'
export const REVIEW_UNLOCK_SUCCESS = 'REVIEW_UNLOCK_SUCCESS'
export const REVIEW_UNLOCK_FAIL = 'REVIEW_UNLOCK_FAIL'