export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

export const USER_CHANGEPASSWORD_REQUEST = 'USER_CHANGEPASSWORD_REQUEST'
export const USER_CHANGEPASSWORD_SUCCESS = 'USER_CHANGEPASSWORD_SUCCESS'
export const USER_CHANGEPASSWORD_FAIL = 'USER_CHANGEPASSWORD_FAIL'

export const USER_FORGOTPASSWORD_REQUEST = 'USER_FORGOTPASSWORD_REQUEST'
export const USER_FORGOTPASSWORD_SUCCESS = 'USER_FORGOTPASSWORD_SUCCESS'
export const USER_FORGOTPASSWORD_FAIL = 'USER_FORGOTPASSWORD_FAIL'

export const USER_NEW_PASSWORD_REQUEST = 'USER_NEW_PASSWORD_REQUEST'
export const USER_NEW_PASSWORD_SUCCESS = 'USER_NEW_PASSWORD_SUCCESS'
export const USER_NEW_PASSWORD_FAIL = 'USER_NEW_PASSWORD_FAIL'

// Admin
// Find all User Admin (Lock and Unlock)
export const USER_ALL_REQUEST = 'USER_ALL_REQUEST'
export const USER_ALL_SUCCESS = 'USER_ALL_SUCCESS'
export const USER_ALL_FAIL = 'USER_ALL_FAIL'

// Find User Page Admin
export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_RESET = 'USER_LIST_RESET'

// Find User Page Detail Admin
export const USER_LIST_DETAIL_REQUEST = 'USER_LIST_DETAIL_REQUEST'
export const USER_LIST_DETAIL_SUCCESS = 'USER_LIST_DETAIL_SUCCESS'
export const USER_LIST_DETAIL_FAIL = 'USER_LIST_DETAIL_FAIL'

// Block User Admin
export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'

// Unlock User Admin
export const USER_UNLOCK_REQUEST = 'USER_UNLOCK_REQUEST'
export const USER_UNLOCK_SUCCESS = 'USER_UNLOCK_SUCCESS'
export const USER_UNLOCK_FAIL = 'USER_UNLOCK_FAIL'

// Update User Admin
export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET'

// Shipper
// Register Shipper
export const SHIPPER_REGISTER_REQUEST = 'SHIPPER_REGISTER_REQUEST'
export const SHIPPER_REGISTER_SUCCESS = 'SHIPPER_REGISTER_SUCCESS'
export const SHIPPER_REGISTER_FAIL = 'SHIPPER_REGISTER_FAIL'

//Verify Register Shipper
export const SHIPPER_VERIFY_REGISTER_REQUEST = 'SHIPPER_VERIFY_REGISTER_REQUEST'
export const SHIPPER_VERIFY_REGISTER_SUCCESS = 'SHIPPER_VERIFY_REGISTER_SUCCESS'
export const SHIPPER_VERIFY_REGISTER_FAIL = 'SHIPPER_VERIFY_REGISTER_FAIL'
